### ISSUE TITLE
angularRequireMatchingFilename is not applicable for directive

### ISSUE THREAD

**Issue by kuceram** [tregusti/jscs-angular#23]
Having a setup:

```
"angularRequireMatchingFilename": {
    "component": "pascal",
    "filename": "dash"
  }
```

is in conflict with Angular for directives as they needs to start with lower case. (https://docs.angularjs.org/error/$compile/baddir?p0=SomeDirective)

**Comment by tregusti** [comment]
Thank you for reporting this issue. How would you like it to behave? Just ignore the matching on directives if rule is set to be PascalCase? Or fallback to camelCase? Or should the rule specification be more specific in what rules matches what?

Ideas are welcome!

**Comment by kuceram** [comment]
Hard question... In my opinion, I would do a fallback to camel-case in case of directives.

**Comment by kuceram** [comment]
Works fine, thx!
